on:
  push:
    branches:
      - master
name: GearBot Updater
jobs:
  deploy:
    name: GearBot Updater
    runs-on: ubuntu-latest
    steps:
      - name: Determine update type
        uses: gearbot/update-action@master
      - name: Trigger update
        uses: AEnterprise/discord-webhook@master
        env:
          DATA: '{"key": "${{ secrets.UPDATE_KEY }}","type": "_UPDATE_STRATEGY_"}'
          DISCORD_WEBHOOK: ${{ secrets.UPDATE_URL }}
          PLACEHOLDER_KEY: '_UPDATE_STRATEGY_'


